// generated by stringer -type=ErrorCode; DO NOT EDIT

package meechum

import "fmt"

const _ErrorCode_name = "OKWARNINGFATAL"

var _ErrorCode_index = [...]uint8{0, 2, 9, 14}

func (i ErrorCode) String() string {
	if i+1 >= ErrorCode(len(_ErrorCode_index)) {
		return fmt.Sprintf("ErrorCode(%d)", i)
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
